### ISSUE TITLE
CDN s3 url not compatible with subdomains

### ISSUE THREAD

**Issue by YassineElbouchaibi** [wundergraph/cosmo#1144]
Hello, it seems like the added support for AWS S3 URLs for CDNs broke support for path style urls with nested subdomain (where hostname has more than 2 dots) e.g. minio.east.domain.com/mybucket.

A workaround is to set S3_ENDPOINT to the wanted origin and set the hostname in the s3 url to a dummy value without dots e.g. https://-/mybucket

Let me know if I missed something

**Comment by AndreasZeissner** [comment]
Hi @YassineElbouchaibi  thanks for pointing that out, 

we are already working on the issue and will provide a fix.

**Comment by AndreasZeissner** [comment]
Hi @YassineElbouchaibi,

https://github.com/wundergraph/cosmo/pull/1145

it is on review.

**Comment by AndreasZeissner** [comment]
Hi @YassineElbouchaibi, 

can you please try using the new release: https://github.com/wundergraph/cosmo/releases/tag/controlplane%400.105.1

**Comment by YassineElbouchaibi** [comment]
It works great, thanks for the quick turnaround!
