### ISSUE TITLE
[BUG] : IAM user with privileged roles at project level

### ISSUE THREAD

**Issue by priyanshukumar397** [wundergraph/cosmo#1174]
### Component(s)

router

### Component version

latest

### wgc version

latest

### controlplane version

latest

### router version

latest

### What happened?

 Detailed paths

Introduced through: resource › google_project_iam_member[cosmo-service-account-permissions]

![image](https://github.com/user-attachments/assets/95111877-2401-4f76-868f-f6be27a9c4aa)

```
resource google_project_iam_member "cosmo-service-account-permissions" {
    role = "roles/iam.serviceAccountUser"
    project = var.project
    member = "serviceAccount:${google_service_account.cosmo-sa.email}"
}
```
**_`https://github.com/cosmo/blob/main/infrastructure/router/modules/google-cloudrun/iam.tf`_**

This issue is...

IAM user has Service Account User or Service Account Token Creator role assigned at project level
The impact of this is...

Users can impersonate service accounts and abuse the elevated permissions
You can resolve it by...

Remove roles/iam.serviceAccountUser and roles/iam.serviceAccountTokenCreator from project level bindings

**Comment by AndreasZeissner** [comment]
Hi @priyanshukumar397,

thanks for opening an issue, 

this is necessary for cloud run to work properly in this scenario and no security concern. 

It follows the official docs, please have a look at https://cloud.google.com/run/docs/configuring/services/service-identity

**Comment by priyanshukumar397** [comment]
Ok thanks for pointing out :)
