### ISSUE TITLE
New server response format when not 200 code in playground looks unreadable

### ISSUE THREAD

**Issue by flymedllva** [wundergraph/cosmo#1185]
### Component(s)

studio

### Is your feature request related to a problem? Please describe.

I extremely dislike the way it now shows responses not having a 200 code

<img width="1111" alt="Screenshot 2024-09-18 at 12 24 37" src="https://github.com/user-attachments/assets/21b9574e-5ce5-4d20-92ed-6f86e3fac436">

1. it's unreadable, although the idea to show what came over HTTP is understandable, but it's better to add some custom fields to the standard GraphQL response structure. Now I don't understand how to try to read responseBody during debugging, and other fields don't give useful load
2. We subgraphs return 4** error codes in case of non-significant problems, 5** in case of unknown server errors. At the same time they describe the standard GraphQL response structure, deviations from this logic are possible only in case of some serious problems, but it seems Playground should be used mainly for debugging, why should I deviate from this structure trying to invent another one?

### Describe the solution you'd like

- Return to the old format
- Extend the standard GraphQL answer with fields that you think should be useful for non-200 codes
- Do not change the structure of the response display for non-200 codes

**Comment by thisisnithin** [comment]
Hi @flymedllva . As we cover more use cases we update the ui accordingly. We have an idea on how this can be improved. Thanks for the insight.

**Comment by flymedllva** [comment]
Hi! @thisisnithin 
Is there no information on what this will look like in the future? Is it possible at least for `4**` response codes not to change the GraphQL structure of the response?

**Comment by thisisnithin** [comment]
Hi, this is in progress as part of a bigger PR
