### ISSUE TITLE
Playground stopped outputting Response Trace & Query Plan for `4**` and `5**` codes

### ISSUE THREAD

**Issue by flymedllva** [wundergraph/cosmo#1282]
### Component(s)

router, studio

### Component version

0.126.0

### wgc version

0.64.1

### controlplane version

-

### router version

0.126.0

## Description

After the recent changes https://github.com/wundergraph/cosmo/issues/1185 to Playground, it has stopped outputting Response Trace & Query Plan for `4**` and `5**` codes, although the router does return a valid response for this one

I still don't understand why different output is drawn for different response codes, instead of an error message...

**Comment by thisisnithin** [comment]
Closing as duplicate of #1185 as it is already being addressed. Thank you.
