### ISSUE TITLE
[Feature Request] Add support for response compression

### ISSUE THREAD

**Issue by vasek** [wundergraph/cosmo#153]
We're working with large schema and responses (up to 10s of MB). Cosmo router currently doesn't support compression of  response compression between client and router and between the router and subgraphs to cosmo router which makes it very slow for larger responses.

**Comment by StarpTech** [comment]
WunderGraph commits fully to Open Source and we want to make sure that we can help you as fast as possible.
The roadmap is driven by our customers and we have to prioritize issues that are important to them.
You can influence the priority by becoming a customer. Please contact us [here](https://form.typeform.com/to/oC6XATf4).

**Comment by jensneuse** [comment]
Good idea. Keeping it open to not forget about it. Currently no priority.

**Comment by StarpTech** [comment]
Closed in favor of https://github.com/wundergraph/cosmo/issues/602
