### ISSUE TITLE
[Feature Request] Cache results of parsing and validation

### ISSUE THREAD

**Issue by vasek** [wundergraph/cosmo#156]
To speed up responses of repeated queries it'd be great to cache results of request parsing and validation as it adds some overhead and it's not necessary to run every time (parse cache can be indefinite, validation cache should be flushed when loading a new schema). 

The router already caches the execution plan for queries. Btw, is there a particular reason to cache it for only 1 hour?
https://github.com/wundergraph/cosmo/blob/cc586ccbe2486ae8e8a6f45bbf1d8cabf55080fa/router/core/graphql_handler.go#L119-L120

**Comment by jensneuse** [comment]
We have updated the behavior and now cache as much as we can.
