### ISSUE TITLE
abstractlogger & byte-template have no license, and this poisons the project from a legal standpoint

### ISSUE THREAD

**Issue by jonathanbaker7** [wundergraph/cosmo#208]
One of our engineering team just asked us if they can bring in the Cosmo package.  We ran a scan using FOSSA (our security and license tool) and it flagged the [AbstractLogger](https://github.com/jensneuse/abstractlogger) project (direct dependency), and the [byte-template](https://github.com/jensneuse/byte-template) project (direct dependency).  Those projects don't have a license attached to them.

This may sound trivial, but the laws in the United States are clear.  Any code which doesn't have a license is "all rights reserved".  GitHub says this explicitly in the [license documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository):

> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Can someone just attach the same Apache 2.0 license to these projects, to let us move forward?

**Comment by jensneuse** [comment]
fixed

**Comment by jonathanbaker7** [comment]
Thank you!
