### ISSUE TITLE
List of one element in variables

### ISSUE THREAD

**Issue by ZirgVoice** [wundergraph/cosmo#271]
### Component(s)

router

## Description
I have arguments that are an array, when passing only one element not wrapped in square brackets I get the error `Cannot return null for non-nullable field ...`, without using a router the same query works fine. The problem occurs only with variables, with inline variables everything is fine.

## Steps to Reproduce
Query:
```gql
query ContentPackMany($pagination: PageArguments!, $filtering: ContentPackFilter) {
  contentPackMany(pagination: $pagination, filtering: $filtering) {
    edges {
      node {
        id
      }
    }
  }
}
```
Variables:
```json
{
  "pagination": {
    "first": 10
  },
  "filtering": {
    "locationIDManyVS": "01HF6W8TW637RBETVCD9KGRR08"
  }
}
```
Filter input:
```gql
input ContentPackFilter {
  ...
  locationIDManyVS: [ID]
  ...
}
```

## Expected Result
The router must accept one element from the list, not wrapped in square brackets, and pass the request to the service.
## Actual Result
The router gives an error. The request does not reach the service
```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Query.contentPackMany.contentPackMany.",
      "path": [
        "contentPackMany",
        "contentPackMany"
      ]
    }
  ],
  "data": null
}
```

### Component version

v0.33.1

**Comment by flymedllva** [comment]
Hi, I have a similar problem. Just like it was written in the issue before the router was updated to some new version (unfortunately, I did not follow it). After the update, such a Path does not work for me at all. When adding a `Person` to the `Client`, it writes an error

```
query Test {
  me { # -> Person
    client { # -> Client
      person { # -> Person 1 error occurred:\n\t* nodesResolvableVisitor: could not select the datasource to resolve Client.person on a path query.me.client.person
        email
      }
    }
  }
}
```
at the same time, such a request works
```
query Test {
  me { # -> Person
    client { # -> Client
      id
    }
  }
}
```

I can't provide a complete scheme, but there are problems with this kind of nested queries. In general, because of this, it is impossible to use Cosmo Router, there are no such problems in Apollo Router

**Comment by flymedllva** [comment]
I tried to get a plan using `wccp router compose`, and I can't find all the fields for the Client type, I don't know if this is normal behavior, but they don't work when trying to download from Playground.

```json
...
{"typeName":"Client","fieldNames":["serviceDraft","id"]}
...
```

```graphql
query Test {
  me { # -> Person
    client { # -> Client
      number # -> String nodesResolvableVisitor: could not select the datasource to resolve Client.number on a path query.me.client.number
    }
  }
}
```

**Comment by StarpTech** [comment]
@flymedllva please create a separate issue with a full reproduction (schema, queries attached). Thank you.

**Comment by devsergiy** [comment]
@ZirgVoice we could not reproduce your issue with the latest version

Please open a new issue if you still experience this problem

Thanks

**Comment by voslartomas** [comment]
> I tried to get a plan using `wgc router compose`, and I can't find all the fields for the `Client` type, I don't know if this is normal behavior, but they don't work when trying to download from Playground.
> 
> ```json
> {"typeName":"Client","fieldNames":["serviceDraft","id"]}
> ```
> 
> ```graphql
> query Test {
>   me { # -> Person
>     client { # -> Client
>       number # -> String nodesResolvableVisitor: could not select the datasource to resolve Client.number on a path query.me.client.number
>     }
>   }
> }
> ```

Created this issues, which seems same #442
