### ISSUE TITLE
Show subgraph name in trace

### ISSUE THREAD

**Issue by clayne11** [wundergraph/cosmo#364]
### Is your feature request related to a problem? Please describe.

At Uber, our routing uses the same URL for every service and our networking router looks at a specific header to determine which service to route a request to. Currently, the traces only show the URL (which is always the same), and I have to dig into the headers to see the service name.

It would be great to see the subgraph name instead of / as well as the URL:
<img width="865" alt="Screenshot 2023-12-13 at 11 25 22" src="https://github.com/wundergraph/cosmo/assets/2831444/0a80f338-7349-4a98-b67e-3f6dd1ee17d9">

### Describe the solution you'd like

Currently the title of the box says "Fetch from subgraph <#>". Replace this with "Fetch from subgraph < name > ".

**Comment by jensneuse** [comment]
I don't think we need this by default, but maybe you could contribute a way to make this configurable so you can enable it for your use case?

**Comment by clayne11** [comment]
Is this not just a better experience, though? Seeing a subgraph name (that
is user configured) vs seeing a # (which is an implementation detail of the
router / control plane) is easier to reason about.

**Comment by jensneuse** [comment]
I might be missing something. When I use the Playground in Cosmo Studio, it shows the subgraph names like so:

<img width="1089" alt="image" src="https://github.com/wundergraph/cosmo/assets/11737109/4b302a82-32d6-47dd-9c50-2821bf17dec3">

I assume you're using the Router without Studio, so maybe we're configuring something differently here. The composition yaml should allow us to forward the names of each subgraph to the trace, I'm just not sure what's missing.

**Comment by Aenimus** [comment]
@jensneuse introspection queries look like the image attached. I think this is an introspection trace. Can you confirm @clayne11?

**Comment by clayne11** [comment]
Nope not an introduction query. This is just a normal query that hits a few
subgraphs. I’m using the router with a static config file created with the
WGC CLI.

**Comment by jensneuse** [comment]
We currently don't intend to improve this, so I'm closing the issue. That said, we're open to a contribution if you'd like to improve this. I think it would be useful, but our main use case is to use ART with the studio.

**Comment by Aenimus** [comment]
Hi @clayne11 

We implemented this recently. Please update to the latest router.
