### ISSUE TITLE
Persisted operations from apollo client returns 500

### ISSUE THREAD

**Issue by voslartomas** [wundergraph/cosmo#402]
### Component(s)

Controlplane

## Description

We are trying to move from Apollo router to Cosmo router and the thing is we are using APQ (Automated Persisted Queries) in apollo client, which expects first send hashed operation and if it does not exist on the server it will send another request with query content so router can cache it. But cosmo router sends 500 response and is not able even trigger second request from client. Is this something known as you don't support apollo's APQ for instance? Or is this a bug?

### Component version

v0.47.2 (controlplane)

## Environment
OS: (e.g., "Ubuntu 20.04")
Package Manager: pnpm, npm, yarn, etc
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by voslartomas** [comment]
It actually needs CDN deployed as well, but even after that it returns 400 Persisted query not found, I would expect that if query does not exist it will register it.

**Comment by jensneuse** [comment]
Cosmo Router supports Persisted Operations but doesn't currently support APQ.

**Comment by voslartomas** [comment]
> Cosmo Router supports Persisted Operations but doesn't currently support APQ.

I see, thank you
