### ISSUE TITLE
Composition error with @override and @key directives

### ISSUE THREAD

**Issue by voslartomas** [wundergraph/cosmo#427]
### Component(s)

composition

## Description

Trying to compose multiple subgraphs having entity with `@key` directive in our monolith graph and trying to migrate to new service fails with an error.

## Steps to Reproduce

monolith
```GraphQL
type Opportunity @key(fields: "id") {
  id: ID!
  activeTaskCount: Int!
}
```

new service
```GraphQL
type Opportunity @key(fields: "id") @shareable {
  id: ID!
  activeTaskCount: Int! @override(from: "monolith")
}
```

## Expected Result

To be able to compose such subgraphs.

## Actual Result

```
 bento1a                      │ The object "Opportunity" defines the same fields in multiple subgraphs without the "@shareable" directive:             │
│                              │  The field "activeTaskCount" is defined and declared "@shareable" in the following subgraph: "newservice-bento1a".          │
│                              │  However, it is not declared "@shareable" in the following subgraph: "monolith".     
```

### Component version

0.15.0

**Comment by Aenimus** [comment]
Hi @voslartomas

I cannot replicate this.

I am assuming the type in the first graph—the monolith—is also supposed to be "Opportunity" (no name is defined in your example).

Please make sure you are using the latest version of everything, and that you have published the latest version of all your subgraphs.

If the problem persists, please attach everything relevant (subgraph schemas), or create a failing test in https://github.com/wundergraph/cosmo/blob/main/composition/tests/override.test.ts.

**Comment by voslartomas** [comment]
Yes, correct my bad, I fixed it in description. I will try to replicate in your tests and create PR.

Also I assume that it is enough to have latest controlplane? I updated it just yesterday.

**Comment by Aenimus** [comment]
@voslartomas Yep, latest wgc and control plane.

I tried the following test, which resulted in no errors:

```
test('that there are no errors', () => {
  const { errors } = federateSubgraphs([subgraphR, subgraphS]);
  expect(errors).toBeUndefined();
});

const subgraphR: Subgraph = {
  name: 'subgraph-r',
  url: '',
  definitions: parse(`
    type Query @shareable {
      dummy: String!
    }
    
    type Entity @key(fields: "id") {
      id: ID!
      name: Int!
    }
  `),
};

const subgraphS: Subgraph = {
  name: 'subgraph-s',
  url: '',
  definitions: parse(`
    type Entity @key(fields: "id") @shareable {
      id: ID!
      name: Int! @override(from: "subgraph-r")
    }
  `),
};```

**Comment by voslartomas** [comment]
Also I've got whole registry running in our staging, so I could give you access so you can see that for yourself we have only 2 graphs there currently and composition fails (on different type, but same type of error).

**Comment by Aenimus** [comment]
@voslartomas It is better if you create a PR with a minimal reproduction of the issue.

I added shareable to the Query to force the graph to be interpreted as a V2 graph. It works with or without it.

**Comment by voslartomas** [comment]
I am not able to replicate it in tests, but also look at this 

https://github.com/wundergraph/cosmo/pull/428/files

This new test should fail as both subgraphs are defining same query without shareable and override, which should alway fail, but it is not?

**Comment by Aenimus** [comment]
@voslartomas When a subgraph is intereprested to be a V1 subgraph (in this case, both of these subgraphs), all fields are shareable by default.

If you cannot replicate in tests, please check you have definitely published the correct schema.

**Comment by voslartomas** [comment]
And how can I say to the testcase that those subgraphs are v2? Without that trick of `@shareable` on Query which would make every field shareable I guess?

**Comment by voslartomas** [comment]
Actually I was able to accidentally replicate the issue, problem is with name of the subgraph with `override(from:"sub1")` this actually happens when there is no such graph defined in registry.

And this happens for us, because we are forced to use different names for subgraphs for each cluster, like `sub1-staging`, `sub1-productiona` instead of simply `sub1` and we are referencing in our schema only `override(from:"sub1")` which does not exists. Not sure how to go around this problem with cosmo.

**Comment by Aenimus** [comment]
@voslartomas Please can you add the replication to the PR?

**Comment by voslartomas** [comment]
It is there actually, so this is not composition problem, but registry problem, or maybe I am missing something to be able to defined one subgraph in multiple envs (with different routing url) but same name?

**Comment by voslartomas** [comment]
With each `npx wgc subgraph publish ` it seems it is taking name as unique identifier, so it will rewrite routing url etc.

**Comment by voslartomas** [comment]
I think we can close this one and I will create new issue with better description of what is our problem now.
