### ISSUE TITLE
Problems with @override (from argument) directive and different environments

### ISSUE THREAD

**Issue by voslartomas** [wundergraph/cosmo#435]
### Component(s)

controlplane, studio

### Is your feature request related to a problem? Please describe.

We have multiple environments and clusters, like staging productionA, productionB etc. And with Cosmo we need to define unique name for each subgraph per environment, because with each `npx wgc subgraph publish` command with the same name (but different labels - used for environments) it will rewrite subgraph with new labels. This is problem as we need to have single schema definition like 

```
type Query {
  test: String! @override(from: "subgraph1")
}
```

But now we are forced to create names of subgraphs like `subgraph1-staging`, `subgraph1-productionA` etc. Which then makes problems as composition cannot find proper name of subgraph.

### Describe the solution you'd like

Possible solution would be to be able to have same name of subgraphs for different environments like in table below.

| Subgraph | Routing URL | Labels |
|--------|--------|--------|
| subgraph1 | http://subgraph1.staging.svc.local/graphql | --env=staging |
| subgraph1 | http://subgraph1.produciton.svc.local/graphql | --env=production |
| subgraph1 | http://subgraph1.production2.svc.local/graphql | --env=production2 |

Then we could reference simply with

```
type Query {
  test: String! @override(from: "subgraph1")
}
```

**Comment by Aenimus** [comment]
Hi @voslartomas,

Namespacing will solve this issue, and it has high priority on our internal roadmap.

Currently, as you know, subgraphs must have a unique name per organization. Namespacing will allow an organization to contain multiple subgraphs of the same name that are differentiated by their namespace.

I'll try to provide updates when possible.

**Comment by Aenimus** [comment]
@voslartomas Namespaces have been implemented.

Namespaces are the missing constructs for grouping and isolating graphs; for example, in different environments like staging and production. Your existing graphs should now be in the default namespace; no migration is required. You can [move](https://cosmo-docs.wundergraph.com/cli/federated-graph/move) graphs around using the corresponding subgraph or federated-graph move command.

Make sure to update the CLI, e.g., `npm install -g wgc@latest`. 

Also note that the FEDERATED_GRAPH_NAME variable for the router is no longer required.

Twitter post:
https://twitter.com/dustindeus/status/1750960283076501530

Documentation:
https://t.co/i6QeB8QfT8

**Comment by jensneuse** [comment]
As David said, this should be solved through namespaces. Please re-open if you have any further issues with this approach.
