### ISSUE TITLE
/live and /ready endpoints requests are logged as info + included in tracing in studio

### ISSUE THREAD

**Issue by voslartomas** [wundergraph/cosmo#438]
### Component(s)

router

## Description

Logs are being polluted with /ready and /live request logs, it could be probably debug only? As if we change log level to error only we will lost information at the start of the pod.

And these requests show up inside tracing in studio.

### Component version

0.54.2

## Environment
OS: (e.g., "Ubuntu 20.04")
Package Manager: pnpm, npm, yarn, etc
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jensneuse** [comment]
Should be fixed in the latest version. Please re-open if the problem still exists.
