### ISSUE TITLE
Is that possible to contribute a piece of content to your engineering blog?

### ISSUE THREAD

**Issue by trkohler** [wundergraph/cosmo#451]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

I want to contribute to WunderGraph engineering blog and not sure how I can do that.

### Describe the solution you'd like

It would be awesome to contact someone responsible for the engineering blog of Wundergraph so that person would tell me what are conditions to accept a contribution.

### Describe alternatives you've considered

I am considering to write to other GraphQL engineering blogs.

### Additional context

I work at the Zalando GraphQL platform, organize Berlin GraphQL, interested in the Open Federation project, and write primarily in Rust and TypeScript.

**Comment by jensneuse** [comment]
Hey, what sort of contribution are you looking to add? In general we're open to the idea. Let's have a chat. You can book a meeting with Stefan, he's responsible for communications and events: https://cal.com/stefan-avram-wundergraph
