### ISSUE TITLE
Enable helm chart to use existing secrets

### ISSUE THREAD

**Issue by PeteMac88** [wundergraph/cosmo#453]
### Component(s)

helm

### Is your feature request related to a problem? Please describe.

The problem with the current helm chart is that you need to provide secret values in plain text in the `values.yaml`. For users who follow a gitops workflow, this is not the ideal solution because the secrets need to be pushed into a repo.

### Describe the solution you'd like

Normally helm chart provide a possibility to define an existing secret name for the chart. In case this value is provided the helm chart does not create its secret resource.

**Comment by PeteMac88** [comment]
I saw that the router chart contains the `extraEnvVarsSecret`  value that can be used to set the `GRAPH_API_TOKEN` env variable. The other charts do not have the possibility to set the env variables through a preexisting secret

**Comment by jensneuse** [comment]
Hey, I think I understand the request and it seems plausible to me. We're adding it to the roadmap. Currently there's no timeline, but I'll keep , you posted.

**Comment by PeteMac88** [comment]
@jensneuse I could help with this if you want? In my opinion, that's a very important part of helm charts often neglected but to use it in a production environment you need the support of secrets.

**Comment by jensneuse** [comment]
Hey, you could open a PR with a potential fix. We'd still have to find resources for a review but it might help, sure.

**Comment by MnLujan** [comment]
Hi guys, I join @PeteMac88 request; I think it's indispensable to avoid having sensitive credentials in Cosmo values.yaml.

**Comment by jensneuse** [comment]
> Hi guys, I join @PeteMac88 request; I think it's indispensable to avoid having sensitive credentials in Cosmo values.yaml.

It sounds important to you. Can we expect a PR?

**Comment by jensneuse** [comment]
#512 addresses this
