### ISSUE TITLE
Self hosted cosmo needs billing plan

### ISSUE THREAD

**Issue by PeteMac88** [wundergraph/cosmo#454]
### Component(s)

controlplane, studio

## Description

I used the helm chart to run cosmo in our Kubernetes cluster since we decided to self-host. The problem is that it seems there is a billing plan required for different actions e.g. creating a new organization. Is this intentional?

## Steps to Reproduce

Install cosmo in k8s cluster with helm chart and try to create a new organization.

## Expected Result

Organization is created with given name

## Actual Result

An error is shown

![image](https://github.com/wundergraph/cosmo/assets/46486024/33670718-ad20-452f-b4ab-f28e36c539fc)

### Component version

0.0.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Package Manager: pnpm, npm, yarn, etc
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jensneuse** [comment]
Hey, our goal is to disable billing on premises altogether. We'll take a look when resources are available.

**Comment by jensneuse** [comment]
Hey, we've investigated this. It's not complex to fix and we've prioritized this to be implemented soon. Expect an update within the next 2 weeks.

**Comment by PeteMac88** [comment]
@jensneuse Thanks :)

**Comment by StarpTech** [comment]
This has been fixed. Please try out the last release.
