### ISSUE TITLE
Playground could take schema from registry not from introspection

### ISSUE THREAD

**Issue by voslartomas** [wundergraph/cosmo#473]
### Component(s)

studio

### Is your feature request related to a problem? Please describe.

Due to security reasons we don't want to expose introspection in our production clusters, but that is a problem with Cosmo's playground as it relies on introspection, without that we are not able to use it.

### Describe the solution you'd like

It could automatically take latests compose schema from registry instead.

**Comment by jensneuse** [comment]
It's a good idea. This would also increase the startup time of the playground for large schemas. Creating a ticket for the team. Updating progress here. Currently no priority.

**Comment by jensneuse** [comment]
It's in progress.

**Comment by voslartomas** [comment]
That was quick, thank you!
