### ISSUE TITLE
Wildcard server in router to be able to get /graphql/NameOfTheQuery

### ISSUE THREAD

**Issue by voslartomas** [wundergraph/cosmo#474]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

We are using named queries in our client like this, but cosmo router is expecting only `/graphql`

https://router-dev.com/graphql/GetUserInfo

### Describe the solution you'd like

We would like to be able to define wildcard mask for main /graphql endpoint.

**Comment by Aenimus** [comment]
This is already available through `GRAPHQL_PATH`.
Please see the attached screenshot:
<img width="1094" alt="Screenshot 2024-02-01 at 21 42 02" src="https://github.com/wundergraph/cosmo/assets/47415099/09fec51f-8b65-402d-a6c9-3b949b10cdb8">

A full list of router configuration variables can be found here:
https://cosmo-docs.wundergraph.com/router/configuration#router

Does this solve your issue?

**Comment by jensneuse** [comment]
Please re-open if the proposed solution doesn't work.
