### ISSUE TITLE
No Federated and Subgraphs after update

### ISSUE THREAD

**Issue by PeteMac88** [wundergraph/cosmo#480]
### Component(s)

controlplane

### Component version

latest

### wgc version

latest

### controlplane version

latest

### router version

latest

## Description

After the update to the latest helm chart the Federated Graph and Subgraphs are not shown anymore in the detail views for the (sub)graph. In the Organization Dashboard we can still see the (sub)graphs but as soon as we want to get detailed information the page shows an error. The network tab in the developer tools shows that the `/wg.cosmo.platform.v1.PlatformService/GetFederatedGraphs` request returns a result but the `/wg.cosmo.platform.v1.PlatformService/GetFederatedGraphByName` request for this graph returns 
```
{
    "response": {
        "code": "ERR_NOT_FOUND",
        "details": "Federated graph 'admin-app-graph' not found"
    },
    "subgraphs": [],
    "graphRequestToken": ""
}
```

## Steps to Reproduce

Since there is no helm chart versioning its hard to tell which change caused this but I installed the helm chart last week on wednesday. 

## Expected Result

Migration should work

## Environment
OS: (e.g., "Ubuntu 20.04")
Package Manager: pnpm, npm, yarn, etc
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by StarpTech** [comment]
Hi @PeteMac88, thanks for the report please try out the latest version on main.

**Comment by PeteMac88** [comment]
@StarpTech Since we are currently testing the self-hosted version with the helm chart, I just reinstalled everything. I will try to test the migration to a new chart when there is a new release.
