### ISSUE TITLE
helm chart registry

### ISSUE THREAD

**Issue by PeteMac88** [wundergraph/cosmo#481]
### Is your feature request related to a problem? Please describe.

Are the helm charts released to some kind of registry to use them?

### Describe the solution you'd like

Push helm charts to registry

**Comment by MnLujan** [comment]
Hi Guys, this would be great too. I'll keep an eye out for the release of this improvement 👀

**Comment by StarpTech** [comment]
Hi, thank you for opening an issue. We already release them through docker but we haven't set up an automatic release workflow. Coming soon. 

Example:

```yaml
helm install router oci://ghcr.io/wundergraph/cosmo/helm-charts/cosmo \
    --version 0.0.1 \
    --values ./values.yaml
```

**Comment by StarpTech** [comment]
From now on, we publish updates on this channel. Docs: https://cosmo-docs.wundergraph.com/deployments-and-hosting/kubernetes/helm-chart/cosmo-platform
