### ISSUE TITLE
Rewrite header names on propagate to subgraphs

### ISSUE THREAD

**Issue by PeteMac88** [wundergraph/cosmo#503]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

The migration from apollo to wundergraph requires changes to the applications. I think its better to provide similar configuration possibilities as the apollo router/gateway

### Describe the solution you'd like

Extend the header configuration to be able to rename a header when propagating it to subgraphs.

**Comment by StarpTech** [comment]
Hi @PeteMac88, good feedback. Could you elaborate a bit on your case?
