### ISSUE TITLE
cosmo.wundergraph.com keeps refreshing - no interactions possible

### ISSUE THREAD

**Issue by platzhersh** [wundergraph/cosmo#572]
### Component(s)

studio

### Component version

cloud

### wgc version

0.43.2

### controlplane version

cloud

### router version

-

## Steps to Reproduce
1. Login to cosmo.wundergraph.com
2. Try navigate or do anything

## Expected Result
UI should be consistent

## Actual Result
UI keeps refreshing, which prevents me from doing anything at all

### Environment information

Tried on multiple devices and browsers:
- Google Pixel with Firefox Mobile
- MacOS Ventura 13.6.1 with Firefox 123.0b3
- MacOS Ventura 13.6.1 with Chrome 121.0.6167.139
- MacOS Ventura 13.6.1 with Chrome 121.0.6167.139 (incognito, no plugins)
![Bildschirmfoto 2024-02-23 um 19 46 22](https://github.com/wundergraph/cosmo/assets/1445827/c85ecab1-69fb-4c63-94f9-1772d5acab9e)

https://github.com/wundergraph/cosmo/assets/1445827/bfdd3c55-e478-4344-9b0a-64da06cd2b34

**Comment by Aenimus** [comment]
@platzhersh Hello,

I recognise that you have tried multiple devices and browsers. However, I also assume that you’re connecting through the same router. Is it possible to use your mobile device's 4/5G to try? You can also set up a hotspot and connect one of your Mac devices to that hotspot. This will allow us to narrow the culprit down.

Thanks!

**Comment by platzhersh** [comment]
Just tried through mobile network from my phone. Same effect. Can try from my desktop through my hotspot later.

**Comment by Aenimus** [comment]
@platzhersh Hi again,

When you delete your federated graph, does the problem persist? And then creating a new federated graph?

**Comment by platzhersh** [comment]
It was there before i added the federated graph already

**Comment by Aenimus** [comment]
@platzhersh Hi again,

Could you log out and sign up with a different email?

I've never seen anything like this before, and you are the first (to my knowledge) to encounter it.

**Comment by platzhersh** [comment]
Ok this is very weird :D I created another account, this time using the regular email sign up. There it looks fine, no sudden refreshing at all 👌 

My other (initial) account I used the github login, there I do have the issue still.

**Comment by platzhersh** [comment]
One more thing I noticed. The refreshing happens on all subpages (so I can't really reach the, it always refreshes back to the main view), except `/account/invitations`. There it doesn't happen.

**Comment by StarpTech** [comment]
Thanks for opening an issue. We were not able to reproduce it.
