### ISSUE TITLE
Latest wgc fails on every command

### ISSUE THREAD

**Issue by voslartomas** [wundergraph/cosmo#582]
### Component(s)

cli

### Component version

latest

### wgc version

latest

### controlplane version

latest

### router version

latest

## Description

```
Error: Failed to check for updates. You can disable update check by setting env DISABLE_UPDATE_CHECK=true. fetch is not defined
```

And it seems it is failing to install some packages as it needs node version 18?

```
+ npm install -g wgc@latest
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'inquirer@9.2.15',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.10.0' }
npm WARN EBADENGINE }
```

This used to work few days ago.

## Environment
OS: (e.g., "Ubuntu 20.04")
Package Manager: pnpm, npm, yarn, etc
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by thisisnithin** [comment]
Hi @voslartomas, node 16 is at end of life and lots of packages including `wgc` have moved out of it. Please upgrade to atleast node 18 and try again.

**Comment by StarpTech** [comment]
Please refer to https://nodejs.org/en/about/previous-releases#release-schedule. We only support LTS.

**Comment by Aenimus** [comment]
Hi @voslartomas,

Is everything in order after updating node?

**Comment by voslartomas** [comment]
@Aenimus  Hello, it's not such a simple task to upgrade node in our workflow unfortunately, do you know which version introduced this? So we can fix previous version, until we are able to upgrade node?

**Comment by Aenimus** [comment]
@voslartomas Node 16 is [end of life](https://nodejs.org/en/blog/announcements/nodejs16-eol), and it should NOT be used in production. I would make it a company priority to ensure that you have updated Node anywhere that is still using <=16.

If, after updating, the problem persists, please let us know.

**Comment by voslartomas** [comment]
We are not using node in production at all, it is only in our pipelines
