### ISSUE TITLE
ARM Docker build

### ISSUE THREAD

**Issue by jurredejongh** [wundergraph/cosmo#585]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

We are using Tilt.dev to run our architecture locally and I was looking to add the Cosmo Router to this list with Helm/K8S. Unfortunately there are no arm64 images for the router and our team consists mostly out of Mac M-chip users, which means we can't run it in K8S.

### Describe the solution you'd like

Is it possible to add arm64 as architecture type to the Docker build?

**Comment by Aenimus** [comment]
This was previously requested:
https://github.com/wundergraph/cosmo/issues/202

I believe our priority on the matter has unchanged. I think @StarpTech can confirm.

**Comment by StarpTech** [comment]
Right, but is not forgotten and will be addressed.

**Comment by jurredejongh** [comment]
Ah, apparently my search capabilities were not that great yesterday. Thank you! 

Also good to know that it is not forgotten! We are looking for a service for our Federated graph and Cosmo looks very promising. Multi-arch support is something we do need, but I'll find a way around that for now. :)

**Comment by Slickstef11** [comment]
@jurredejongh 

Are you free to hop on a call soon? Would love to see if we could help you out.

https://cal.com/stefan-avram-wundergraph/wundergraph-introduction

**Comment by StarpTech** [comment]
Fixed with https://github.com/wundergraph/cosmo/pull/665
