### ISSUE TITLE
Add support for response compression

### ISSUE THREAD

**Issue by StarpTech** [wundergraph/cosmo#602]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

As a user, I'd like to be able to compress data between the client <-> router to save bandwidth and improve performance.

### Describe the solution you'd like

Response compression is done transparently. The user of the router doesn't need to configure anything. The exchange is done through HTTP headers `Accept-Encoding`. The implementation should support Gzip, Deflate and Brotli as compression methods.

We need to extend the router to compress responses. A very reasonable choice for gzip could be https://github.com/klauspost/compress/tree/master/gzhttp which also serve as good inspiration for the other methods.

**Requirements:**
- No CGO.
- Functionality must be provided in separate Go modules with unit tests and  integration test. See [test suite](https://github.com/wundergraph/cosmo/tree/main/router-tests).
- Use compression defaults that favor a good mix between compute time and space savings.

### Additional context

We use gin as http framework. The router engine transport can be found here https://github.com/wundergraph/cosmo/blob/main/router/core/transport.go

Previous issue #153

**Comment by Rutik7066** [comment]
@StarpTech do we need prehandler and posthandler to decode and encode the request body?

**Comment by Rutik7066** [comment]
Hi @StarpTech I have raised the draft PR. I would appreciate your help with further development. I need to know where I should use compression and decompression functions to achieve the desired results.

**Comment by Rutik7066** [comment]
Hi @StarpTech I need you help in architectural understanding in know in I have to add it as prehandler and posthandler. But I am unable to understand where other prehandler and posthandler is added.

**Comment by StarpTech** [comment]
@Rutik7066 take a look at the referenced issue https://github.com/wundergraph/cosmo/issues/153 Wwe want to support client response compression. This means, a middleware needs to be implemented that overwrites responseWriter to support the compression algorithm. You can use https://github.com/go-chi/chi/blob/master/middleware/compress.go

**Comment by Rutik7066** [comment]
> @Rutik7066 take a look at the referenced issue https://github.com/wundergraph/cosmo/issues/153 We want to support client response compression. This means, a middleware needs to be implemented that overwrites responseWriter to support the compression algorithm. You can use https://github.com/go-chi/chi/blob/master/middleware/compress.go
> This is already almost the full story. If I assistant you more, I could the address the bounty myself 😄 

Got it 🫡

**Comment by Rutik7066** [comment]
Hi @StarpTech work is completed. Could you please review PR

**Comment by leonhfr** [comment]
I'm interested in taking a shot at this, adding my name to the queue!

**Comment by Rutik7066** [comment]
> I'm interested in taking a shot at this, adding my name to the queue!

PR submitted already everything is done. I am waiting for @StarpTech to review the PR

**Comment by Rutik7066** [comment]
Hi @StarpTech could you please review the PR

**Comment by StarpTech** [comment]
Hi @StarpTech, there is a lot going on right now. I promise to review it at the beginning of next week. Thank you for your patience.

**Comment by StarpTech** [comment]
I have decreased the scope of the ticket and therefore also the reward. Thanks for the contribution @Rutik7066

**Comment by Rutik7066** [comment]
@StarpTech  what?

**Comment by Rutik7066** [comment]
@StarpTech I think you know I worked because of 200$ bounty price right. If anything from my side needs to be corrected or completed then you should tell me instead of this thing.

**Comment by StarpTech** [comment]
Hi @Rutik7066,

I appreciate the effort you put into the project. However, it's important to note that the requirements were clearly outlined from the start. We've provided significant guidance throughout this process, which wasn't the intent of the bounty. You have completed response compression, which is only half of the requirement, and therefore received $100 as a reward.

The issue is closed.

Thank you for your understanding and contribution.

**Comment by Rutik7066** [comment]
@StarpTech just because of some guidance on project code ? You are cutting half of the bounty.

**Comment by Rutik7066** [comment]
Okay No problem I guess I have wasted you time as well.
