### ISSUE TITLE
Cache introspection query

### ISSUE THREAD

**Issue by StarpTech** [wundergraph/cosmo#605]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

As a user, I would like to have fast introspection queries. A schema can be very large and currently, it can take several seconds until the router has prepared and respond to the introspection query request. We're talking about scenarios with more 10K+ lines of GraphQL schemas and 5K+ of types.

We can speed this up by caching the entire response in-memory. A schema can only be modified on router restart or after the router has polled an update from the CDN; otherwise, the schema remains stable, so a cache is very efficient in this case.

### Describe the solution you'd like

Please cache the introspection query in memory after it has been computed by the [engine](https://github.com/wundergraph/cosmo/blob/main/router/core/graphql_handler.go#L148). Return a response header e.g. `X-WG-Introspection-Cache: true` to signal that the introspection was served from the cache. When the schema is updated the cache is invalidated.

**Requirements:**
- No CGO.
- Functionality must be provided in separate Go modules with unit tests and integration test. See [test suite](https://github.com/wundergraph/cosmo/tree/main/router-tests).
-  The introspection request should still be tracked in metrics and analytics.

### Additional context

The introspection result is written here on the [responseWriter](https://github.com/wundergraph/cosmo/blob/main/router/core/graphql_handler.go#L148) interface.

Original issue: #155

**Comment by shashank40** [comment]
Hey @StarpTech 
Can you please assign the issue to me.
Even though, just after looking at the issue i cannot explain the full execution plan. But i am thinking around the lines of server-side caching in GraphQL.

We can expand on the discussion as i push more commits to my PR.

/attempt #605

**Comment by StarpTech** [comment]
Hey @shashank40! Just wanted to let you know that the bounty is up for challenge for those who can independently solve the task. We're here to support you with a final review, but it's designed to be a solo challenge. Given your tech background, it might be a tough nut to crack, especially because it demands a deep understanding of Go idioms to meet our high standards. Maybe consider this before diving in and spending your time on it.

**Comment by shashank40** [comment]
@StarpTech 
Why not give it a try?
And for that part, i have worked briefly with go (and motivated to work more) in my daily job and so you see only python ts and js in my profile.

**Comment by StarpTech** [comment]
Of course, you can try it. There is nothing to do here on our end.

**Comment by ologbonowiwi** [comment]
I have yet to learn the codebase, but I'd like to /attempt it.

Will drop the attempt in case I don't end up working on it

**Comment by StarpTech** [comment]
Hi @ologbonowiwi, please keep in mind that bounties are standalone tasks (read the bounty conditions) because you get rewarded for them. If you want to contribute to OSS and believe you need a lot of assistance please don't attempt to the bounty but create a PR.

**Comment by ologbonowiwi** [comment]
Hi @StarpTech, you added the same links for [engine](https://github.com/wundergraph/cosmo/blob/main/router/core/graphql_handler.go#L148) and [responseWriter](https://github.com/wundergraph/cosmo/blob/main/router/core/graphql_handler.go#L148). Is that right? If not, can you update the links on the issue's description?

**Comment by StarpTech** [comment]
Hi @ologbonowiwi, we will shut down the bounty program. Sorry if you had any inconvenience.
