### ISSUE TITLE
Incorrect command in comment in values.yaml for creating graph API token

### ISSUE THREAD

**Issue by BrianSiimAndersenEG** [wundergraph/cosmo#691]
### Component(s)

helm

### Component version

latest

### wgc version

0.49.0

### controlplane version

0.80.2

### router version

-

### What happened?

Within the `values.yaml` in the Helm component, there's a comment on how to create a graph API token for the router:
```
# You need to run `wgc federated-graph create-token mygraph --namespace default` to generate a token
```
This command fails with an `unknown command 'create-token'` error. On the website document another command is specified, and that worked. So maybe the comment should be changed to something like:
```
# You need to run `wgc router token create mygraph_token -g mygraph` to generate a token
```

## Environment
OS: (e.g., "Ubuntu 20.04")
Package Manager: pnpm, npm, yarn, etc
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by Aenimus** [comment]
Hi,

We've created an internal issue to address this. We will fix it in due course.

Thank you for your report and patience!

**Comment by Aenimus** [comment]
Addressed in https://github.com/wundergraph/cosmo/pull/712

Thank you for your report!
