### ISSUE TITLE
router-tests/update-config.sh is broken on main

### ISSUE THREAD

**Issue by clayne11** [wundergraph/cosmo#701]
### Component(s)

router

### Component version

main

### wgc version

main

### controlplane version

main

### router version

main

### What happened?

Checked out main and ran:

➜  router-tests git:(main) cd router-tests
➜  router-tests git:(main) ./update-config.sh
2024/04/05 10:46:37 Error: Unsupported subscription protocol '' at n3 (<eval>:453:41501(37))
exit status 1

I'm unable to update the test config.

## Environment
OS: Mac OS 14.4.1
Package Manager: pnpm 8.15.6

**Comment by Aenimus** [comment]
Fixed with #702 

Thank you for the report!
