### ISSUE TITLE
Reduce wgc package size

### ISSUE THREAD

**Issue by co-sic** [wundergraph/cosmo#738]
### Component(s)

cli

### Is your feature request related to a problem? Please describe.

The size of the wgc package currently is about 140 mb (version 0.51.2), which is way to big. See [pkg-size](https://pkg-size.dev/wgc). I guess that this can be reduced significantly by just removing certain packages from bundling, but of course i could be wrong there.

### Describe the solution you'd like

Way smaller package size.

**Comment by Aenimus** [comment]
Hi @co-sic,

I think this is something that we will continually monitor, address, and improve. However, if ever you see an unreasonable r unexpected increase in the package size, please create a new issue.

For now, I'm going to close this.

Thanks!

The WunderGraph Team
