### ISSUE TITLE
Cannot change away from dark theme in GraphQL router playground

### ISSUE THREAD

**Issue by rickpasetto** [wundergraph/cosmo#744]
### Component(s)

router

### Component version

0.75.0

### wgc version

0.51.3

### controlplane version

cloud?

### router version

0.75.0

## Description
Open up the endpoint to the GraphQL Playground on the router.  It always defaults to dark mode.  Changing the theme in settings has no effect

I can reproduce this problem both running the router locally and by running it self-hosted.

## Steps to Reproduce
- Open up the endpoint to the GraphQL Playground on the router
- Open Settings
- Click "Light" or "System Settings".  It has no effect.  Theme stays dark (and, admittedly, extremely difficult to read).

## Expected Result
- Ability to change theme

## Actual Result
- Cannot change theme from dark theme

<img width="1511" alt="Screenshot 2024-04-19 at 3 51 12 PM" src="https://github.com/wundergraph/cosmo/assets/308993/b8ca1f43-2509-4e4d-9847-ee431604569a">

https://github.com/wundergraph/cosmo/assets/308993/8a2fc47f-4eb4-4919-a16d-4ba55af22f65

## Environment
OS: macOS running Chrome 123.0.6312.124

**Comment by StarpTech** [comment]
Thanks for reporting! Please use the native theme switcher. 
![CleanShot 2024-04-30 at 11 19 15@2x](https://github.com/wundergraph/cosmo/assets/1764424/d3f3862c-20e0-4525-82a3-005331133035)

**Comment by StarpTech** [comment]
Oh, you were referring to the router playground. Got it.

**Comment by rickpasetto** [comment]
I am viewing the studio pointing at a self-hosted router running on AWS. Is it possible that I've misconfigured it somehow?

**Comment by StarpTech** [comment]
I can't validate it with the provided information but it doesn't looks like. Your report is valid. The playground does not support theming. In the Studio, you can only use our own light / dark mode.

**Comment by rickpasetto** [comment]
Hm. But it appears that it is "stuck" in dark mode, even if you choose "light" mode.  I even notice in the playground (cosmo.wundergraph.com) I am unable to switch the theme.
