### ISSUE TITLE
request: Support HTTP GET for persisted queries

### ISSUE THREAD

**Issue by jeffutter** [wundergraph/cosmo#796]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

To facilitate CDN caching, we would like to have support for requesting persisted queries via HTTP Get requests.

Furthermore, some of our existing clients use this scheme and without this ability, a seamless migration to cosmo is not possible.

### Describe the solution you'd like

We would like to see something similar to https://graphql.org/learn/serving-over-http/#get-request but supporting persisted queries. 

Specifically supporting URLs like: `https://domain.com/graphql/persisted_queries/:query_hash` with `variables` as a query argument, the value of which is a JSON encoded map of variables.

**Comment by jensneuse** [comment]
HTTP GET is now supported for Queries in line with how Apollo implemented it.
