### ISSUE TITLE
@openfed__subscriptionFilter validation issues

### ISSUE THREAD

**Issue by xwrs** [wundergraph/cosmo#814]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

Hi, I see a few PRs aiming to implement subscription filtering logic and the changes are really recent.
There are comments in test files containing `@openfed__subscriptionFilter` directives. The code in `181d89d8:router/core/factoryresolver.go@158` which loads field configuration is not populating the SubscriptionFilterCondition field:
```
fieldConfig := plan.FieldConfiguration{
			TypeName:             configuration.TypeName,
			FieldName:            configuration.FieldName,
			Arguments:            args,
			HasAuthorizationRule: l.fieldHasAuthorizationRule(configuration),
//SubscriptionFilterCondition may have been populated here from subscription directive?
		}
```

question is: are subscription filters functioning now or I am missions something or is it still WIP and they are not ready? Thank you

### Describe the solution you'd like

directives for filtering EDFS are implemented as intended and/or documented once available

### Additional context

you have really fantastic product with great potential. currently seriously consider using WG stack to get rid of monolith GraphQL service we have. Once all checkboxes are checked (federated subscriptions using EDFS are only thing that left to assess for our production use) we are going to use self-hosted WG service and once it is showing good results we will consider switching to managed service.

**Comment by xwrs** [comment]
Alright, pulled a last version of main branch and still have to check if filtering functionality is in place. Documentation (or at least draft) would really help. Even though it is really exciting to crawl through the source code and debug it to find how it works (no sarcasm here) the documentation or sample code would really help. cheers

**Comment by Aenimus** [comment]
@xwrs is there somewhere that's stating "field" rather than "fieldPath"? And were the error messaged during composition unclear?

**Comment by xwrs** [comment]
@Aenimus there were no errors during composition. Control plain produces corrupted config. CDN contails following config
```
...
 "subscriptionFilterCondition": {
                    "in": {
                        "json": "[\"{{ args.id }}\"]"
                    }
                }
...
```

instead of
```
...
 "subscriptionFilterCondition": {
                    "in": {
                        "fieldPath": [
                            "id"
                        ],
                        "json": "[\"{{ args.uavId }}\"]"
                    }
                }
...
```

SubscriptionFieldCondition is being deserialized then with empty field path and the filter is not working obviously.

**Comment by Aenimus** [comment]
Thank you for explaining @xwrs.

Would you be able to provide me with the subscription filter in the exact form it was written in the Event-Driven Graph? Even if that form was "incorrect", e.g., defining "field" rather than "fieldPath"?

I will then investigate to understand why such an instance was not caught by composition.

Thanks again!

**Comment by xwrs** [comment]
Simplest filtering seems to be working fine. Plan is to verify if all cases we need can be covered by the `SubscriptionFilterCondition`. Considering it's recursive nature it should be possible.

I will switch to enrichment of this filters based on the context of subscriber (user) now (I mentioned in #774 ). It seems that I have all data I need in resolver context to introduce some kind of middleware. It is possible to do it kinda right way (custom directives) and let schema configure itself. Or just hardcode some middleware calls to external endpoint and obtain enriched filters. But it is totally different issue and topic. Just sharing my excitement.

**Comment by Aenimus** [comment]
Hi @xwrs

The validation logic is now working in the latest release. We did not want to delay the feature, so only the happy path was tested. Now the unhappy paths are also tested and functional. Fun fact: the validation logic was correct but some errors were not propagated due to a missing boolean set. 🙈

We're looking forward to reading your feedback on the new feature!
