### ISSUE TITLE
[aws-lambda-router] Router missing environment variables

### ISSUE THREAD

**Issue by miguelwebtales** [wundergraph/cosmo#871]
### Is your feature request related to a problem? Please describe.

The AWS lambda router currently doesn't accept config router settings GRAPHQL_PATH and PLAYGROUND_PATH.

I am working currently on a pull request.

### Describe the solution you'd like

Be able to setup this configuration variables

**Comment by miguelwebtales** [comment]
Assigned PR to this issue: #908

**Comment by miguelwebtales** [comment]
I created a feature request and a PR #872, that makes this feature request redundant.

**Comment by jensneuse** [comment]
Closing in favour of #872
