### ISSUE TITLE
Composition of Root type field returning Root type fails

### ISSUE THREAD

**Issue by maxrad82** [wundergraph/cosmo#891]
### Component(s)

composition

### Component version

latest

### wgc version

0.57.7

### controlplane version

latest

### router version

latest

### What happened?

Hi,

when trying to compose 2 subgraphs:

**subgraph #1**

type Mutation {
 impersonate(...): Mutation
}

**subgraph #2**

type Book {
  id: ID!
}

type Mutation {
  upsertBook(..): Book
}

The composition fails complaining that we should either transform the Mutation type to an Entity with an @key field or declaring @shareable impersonate in the 2 subgraphs (we can't do this)

I assume that it is a issue related to Root types, the composition succeeds in Apollo graph os

## Environment
OS: (e.g., "Ubuntu 20.04")
Package Manager: pnpm, npm, yarn, etc
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by Aenimus** [comment]
Hi,

Please could you create a PR with a minimal failing test in the composition tests? The best place would be here: https://github.com/wundergraph/cosmo/blob/main/composition/tests/resolvability.test.ts

Thanks,

The WunderGraph Team

**Comment by Aenimus** [comment]
Hi @maxrad82,

Please could you create a PR with a minimal failing test in the composition tests? The best place would be here: https://github.com/wundergraph/cosmo/blob/main/composition/tests/resolvability.test.ts

Thanks,

The WunderGraph Team

**Comment by maxrad82** [comment]
Sure, in which branch should i create the PR ?

**Comment by Aenimus** [comment]
Hi @maxrad82,

You'll have to fork the Cosmo repository, then a new branch with a name relevant to the issue would be great.

Thanks!

**Comment by maxrad82** [comment]
#893

**Comment by Aenimus** [comment]
Hi @maxrad82,

Thank you; it's appreciated! We'll investigate in due course.

**Comment by Aenimus** [comment]
Hi @maxrad82,

This will be fixed in the next release of composition. Regarding your example test (thanks for that), what is the purpose of such a graph?

**Comment by maxrad82** [comment]
Hi

An example of use case is testing authenticated users, the impersonate query gets a user context (jwt token), based on an user id or whatever which is then passed to all subgraphs (token is passed in http headers). That way we can easily test permissions. We don't have interact directly with the anthentication system (login). Just a single gql request

**Comment by Aenimus** [comment]
Hi @maxrad82,

This should be fixed as of [wgc@0.58.6](https://github.com/wundergraph/cosmo/releases/tag/wgc%400.58.6).

Thank you for the report!
