### ISSUE TITLE
bug: Custom scalars always interpreted as string [confirmed]

### ISSUE THREAD

**Issue by belaczek** [wundergraph/cosmo#91]
Hi,
Currently it seems like the cosmo router does not handle custom scalars properly. 
As an example, our subcharts have a custom scalar type `LONG`. When router receives a response from subchart including a long typed field, the router fails with following error:
`"error":"invalid value type 'number' for path /data/_modelMetadata/modelHcn, expecting string, got: 5160. You can fix this by configuring this field as Int/Float/JSON Scalar" `.
In ideal scenario, the router should just passthrough the value without applying any validation. 
Apollo gateway handles this without issues.

Related issue: https://github.com/wundergraph/graphql-go-tools/issues/530

**Comment by Aenimus** [comment]
Hi @belaczek,

Please could you update your router to `0.19.0` and try again?

**Comment by belaczek** [comment]
It's fixed, thank you!
