### ISSUE TITLE
Unsure how to build a subgraph

### ISSUE THREAD

**Issue by thekevinbrown** [wundergraph/cosmo#914]
Hi there,

I'm still working on making [Graphweaver](https://graphweaver.com) compatible with Cosmo. I'm really confused.

My two subgraphs have a `{ _service { sdl } }` query as per the [Apollo federation specification](https://www.apollographql.com/docs/federation/subgraph-spec/#enhanced-introspection-with-query_service). When I run `wgc router compose` I get the following:

```console
Failed to compose: Error: The object "_service" defines the same fields in multiple subgraphs without the "@shareable" directive:
 The field "sdl" is defined in the following subgraphs: "music", "payments".
 However, it is not declared "@shareable" in any of them.
```

By definition (and specification), the `sdl` query is going to return different results per subgraph, so it is not `@shareable`. The Apollo examples do not have any federation directives on the `_service` query.

What am I doing wrong here? Can you please point me to documentation or the working examples for Cosmo so I can figure out what the schema should look like for a subgraph?

**Comment by Aenimus** [comment]
Hi @thekevinbrown,

Composition shouldn't care about the federation boiler plate. Can you share both your SDLs, please?

**Comment by thekevinbrown** [comment]
Thanks for the response!

The specification I linked to has it with a lower-case letter. Can you link me to docs or a specification I should be using instead if the Apollo ones are wrong?

Graphweaver is such a client, so yes, I’m building support for federation now. Hence the confusion.

**Comment by Aenimus** [comment]
Hi @thekevinbrown,

The query root field should be lowercase, yes. But the response type, the GraphQL Object, should be `_Service`, as mentioned. If you attempted to build your SDLs with Apollo you would receive a similar error to that of Cosmo:
``` Non-shareable field "_service.sdl" is resolved from multiple subgraphs: it is resolved from subgraphs "x" and "y" and defined as non-shareable in all of them```

**Comment by Aenimus** [comment]
Scrolling down the same resource you've shared @thekevinbrown:
<img width="778" alt="Screenshot 2024-07-04 at 16 07 34" src="https://github.com/wundergraph/cosmo/assets/47415099/7b6473ea-3bec-4e06-bfb3-8b8e132b8770">

**Comment by thekevinbrown** [comment]
Got it, I'll do that, thanks!
