### ISSUE TITLE
Removing Lint rules breaks CLI check command

### ISSUE THREAD

**Issue by YassineElbouchaibi** [wundergraph/cosmo#988]
v0.93.1 removed linting rule REQUIRE_DEPRECATION_DATE. As a consequence the wgc subgraph check command started failing. Looking at the controlplane logs, it is not able to resolve the relevant definition for that rule as it still exists in DB but not in the code. The command fails with internal error code 13. The rule cannot be disabled from the studio UI as it doesn't exist there anymore. To workaround the issue I manually dropped the entry from the DB in the namespace_lint_check_config table. Going forward I would suggest dropping dead rules from the DB in the DB migrations.

Note: Sorry about formatting, I am using github mobile

**Comment by StarpTech** [comment]
Hi @YassineElbouchaibi, thanks for bringing this to our attention. Your observation is correct. In this situation, a migration was not included. Your fix is sufficient.
